[Interface]
Address = 10.13.13.2
PrivateKey = qMr4MJNx/pr12ZDGSxKysYQtWCuR0GWXBUbKKgCrMnk=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = hxAOm8aOaIEiDCQPQdqzpaD33hIiAuserKsv7RtSOiU=
PresharedKey = G63sCpiGo4pjthCijg74kCmzWpoUqR12M7567C39c10=
Endpoint = 73.170.31.152:51820
AllowedIPs = 10.13.13.0/24
