[Interface]
Address = 10.13.13.2
PrivateKey = wCb+Gba/mCG5eskZhFvq/GN0LL17uMRa88XZIOXUIWo=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = oGKEV4sSlrwDIjedJtBJGtQqoTEXddDRDSGd8LRw4Ew=
PresharedKey = Gj5eZlphyjGKkE3g8VEao+0AMvY7R3jMvRGjUpJO0eA=
Endpoint = 73.170.31.152:51820
AllowedIPs = 10.13.13.0/24
