services:
  attacker:
    image: alpine:latest
    container_name: zt-attacker
    # HTTP access, port probing, TLS testing, advanced proof
    command: sh -c "apk add --no-cache curl bind-tools openssl netcat-openbsd tcpdump && sleep infinity"
    networks:
      edge_net:
        ipv4_address: 172.21.0.30

  frontend:
    build: ./app/frontend
    container_name: zt-frontend
    command: nginx -g 'daemon off;'
    expose:
      - "80"
    volumes:
      - ./infrastructure/step-ca/issued/frontend:/etc/nginx/certs/frontend:ro
      - ./infrastructure/step-ca/certs/ca_chain.crt:/etc/nginx/certs/ca_chain.crt:ro
    networks:
      frontend_private_net: {}
      frontend_api_net:
        ipv4_address: 172.31.11.10
      pomerium_frontend_net: {}
    depends_on:
      - api

  api:
    build: ./app/api
    container_name: zt-api
    expose:
      - "4000"
    volumes:
      - ./infrastructure/step-ca/issued/api:/app/certs/api:ro
      - ./infrastructure/step-ca/certs/ca_chain.crt:/app/certs/ca_chain.crt:ro
      - ./infrastructure/step-ca/secrets/password:/app/certs/key_pass.txt:ro
    networks:
      api_private_net: {}
      frontend_api_net:
        ipv4_address: 172.31.11.11
        aliases:
          - api.local
      api_backend_net:
        ipv4_address: 172.31.12.10
    depends_on:
      - backend

  backend:
    build: ./app/backend
    container_name: zt-backend
    expose:
      - "5000"
    volumes:
      - ./infrastructure/step-ca/issued/backend:/app/certs/backend:ro
      - ./infrastructure/step-ca/certs/ca_chain.crt:/app/certs/ca_chain.crt:ro
      - ./infrastructure/step-ca/secrets/password:/app/certs/key_pass.txt:ro
      - backend_data:/app/data
    networks:
      backend_private_net: {}
      api_backend_net:
        ipv4_address: 172.31.12.11
        aliases:
          - backend.local

  step-ca:
    image: smallstep/step-ca:latest
    container_name: zt-step-ca
    ports:
      - "9000:9000"
    volumes:
      - ./infrastructure/step-ca:/home/step
    environment:
      - STEPPATH=/home/step
    command: step-ca /home/step/config/ca.json --password-file /home/step/secrets/password
    networks:
      control_net:
        ipv4_address: 172.31.30.13
    restart: unless-stopped

  pomerium:
    image: pomerium/pomerium:latest
    container_name: zt-pomerium
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./infrastructure/pomerium/config.yaml:/pomerium/config.yaml:ro
      - ./infrastructure/pomerium/certs:/pomerium/certs:ro
      - pomerium-data:/data/
    environment:
      - POMERIUM_SHARED_SECRET=${POMERIUM_SHARED_SECRET}
      - POMERIUM_COOKIE_SECRET=${POMERIUM_COOKIE_SECRET}
    command: --config /pomerium/config.yaml
    networks:
      edge_net:
        ipv4_address: 172.21.0.20
      pomerium_frontend_net: {}
    depends_on:
      - frontend
    restart: unless-stopped

  verify:
    image: pomerium/verify:latest
    container_name: zt-verify
    networks:
      control_net:
        ipv4_address: 172.31.30.14

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - PEERS=frontend,api,backend
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0/24
      - ALLOWEDIPS=10.13.13.0/24
    volumes:
      - ./infrastructure/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      control_net:
        ipv4_address: 172.31.30.2
    restart: unless-stopped

volumes:
  backend_data:
  pomerium-data:

networks:
  edge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
  frontend_private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.1.0/24
  api_private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.2.0/24
  backend_private_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.3.0/24
  frontend_api_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.11.0/24
  api_backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.12.0/24
  pomerium_frontend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.21.0/24
  control_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.30.0/24
