services:
  frontend:
    build: ./app/frontend
    container_name: zt-frontend
    ports:
      - "80:80"
    networks:
      edge_net:
        ipv4_address: 172.20.0.10
      app_net:
        ipv4_address: 172.21.0.10

  api:
    build: ./app/api
    container_name: zt-api
    ports:
      - "4000:4000"
    networks:
      app_net:
        ipv4_address: 172.21.0.11
    depends_on:
      - backend

  backend:
    build: ./app/backend
    container_name: zt-backend
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.21.0.12
    volumes:
      - backend_data:/app/data

  step-ca:
    image: smallstep/step-ca:latest
    container_name: zt-step-ca
    ports:
      - "9000:9000"
    volumes:
      - ./infrastructure/step-ca:/home/step
    environment:
      - STEPPATH=/home/step
    command: step-ca /home/step/config/ca.json --password-file /home/step/secrets/password
    networks:
      app_net:
        ipv4_address: 172.21.0.13
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto # Not sure if we would have a public IP/domain for containers
      - PEERS=frontend,api,backend
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0/24 # The default internal subnet for WG
      - ALLOWEDIPS =172.20.0.0/16,172.21.0.0/16,10.13.13.0/24 # Traffic can flow between these 3 subnets
    volumes:
      - ./infrastrcture/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

volumes:
  backend_data:

networks:
  edge_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
