services:
  frontend:
    build: ./app/frontend
    container_name: zt-frontend
    networks:
      - edge_net
      - app_net

  api:
    build: ./app/api
    container_name: zt-api
    environment:
      DATABASE_HOST: backend
      DATABASE_PORT: 5432
      DATABASE_NAME: appdb
      DATABASE_USER: appuser
      DATABASE_PASSWORD: apppass
    networks:
      - app_net
      - data_net
    depends_on:
      - backend

  backend:
    image: postgres:16
    container_name: zt-backend
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_net

  step-ca:
    image: smallstep/step-ca:latest
    container_name: zt-step-ca
    ports:
      - "9000:9000"
    volumes:
      - ./infrastructure/step-ca:/home/step
    environment:
      - STEPPATH=/home/step
    command: step-ca /home/step/config/ca.json --password-file /home/step/secrets/password
    networks:
      - app_net
    restart: unless-stopped

  pomerium:
    image: pomerium/pomerium:latest
    ports:
      - 443:443
    restart: always
    environment:
      POMERIUM_ZERO_TOKEN: ${POMERIUM_ZERO_TOKEN}
      XDG_CACHE_HOME: /var/cache
    volumes:
      - pomerium-cache:/var/cache
    networks:
      main:
        aliases:
          - verify.able-snail-8528.pomerium.app
  verify:
    image: pomerium/verify:latest
    networks:
      main:
        aliases:
          - verify

volumes:
  postgres_data:
  pomerium-cache:

networks:
  main: {}
  edge_net:
  app_net:
  data_net: