# TLS configuration
certificate_file: /pomerium/issued/pomerium/tls.crt
certificate_key_file: /pomerium/issued/pomerium/tls.key

# routes
routes:
  # for the frontend
  - from: https://app.zt.local
    to: http://zt-frontend:80
    pass_identity_headers: true
    policy:
      - allow:
          or:
            - domain:
                is: sjsu.edu
  # for the api — routed through frontend nginx which applies mTLS to api
  - from: https://api.zt.local
    to: http://zt-frontend:80/api
    pass_identity_headers: true
    policy:
      - allow:
          or:
            - domain:
                is: sjsu.edu
      
